apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-prometheus-app
spec:
  replicas: {{ .Values.my-app.replicas }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus-site
          image: local.dev/my-prometheus-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9400
