apiVersion: v1
kind: Service
metadata:
  name: my-prometheus-entrypoint
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 80            # Service internal port
      targetPort: 9400    # Container port (must match your Java app)
      nodePort: 30001     # External access port
