apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.Prometheus.replicas }}}
  selector:
    matchLabels:
      app: {{ include "grafana.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "grafana.fullname" . }}
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
