apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ include "grafana.fullname" . }}
  ports:
    - port: 80
      targetPort: 3000
      nodePort: {{ .Values.NodePort.nodePort }}
